Vagrant.configure("2") do |config|

   config.vm.box = "lamp-ubuntu"


   config.vm.network "forwarded_port",
     guest: 80,
     host: 8080,
     host_ip: "127.0.0.1"

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     vb.name = "my_vm"
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.cpus = "2"
   end

end
